### ISSUE TITLE
gpg -decrypt {파일 이름}

### ISSUE THREAD

**Issue by KimEJ** [minwook-shin/ubuntu-korea-l10n-workshop#4]
경우에 따라 다음 에러가 나올 수 있다고 합니다.

`gpg: conflicting commands`

따라서 다음과 같이 쓰는것이 옳다고 합니다
-decrypt -> --decrypt
`gpg --decrypt {파일 이름}`

**Comment by minwook-shin** [comment]
@KimEJ  ece876d 커밋으로 반영되었습니다. 감사합니다. 
이슈를 닫습니다.
